spring:
  application:
    name: 'user-service'
  config:
    import: configserver:http://config-server:8061
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_DSN}
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
  profiles:
    active: 'all'
server:
  port: 8005
  error:
    include-message: always
    include-stacktrace: never
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}